import React from 'react'
import Footer from '../footer/Footer'

const page = () => {
  return (
    <div>
        <div className="mt-20 mb-5">
            <h1 className="text-center font-bold text-2xl my-3">Terms of Use</h1>
        </div>
        <div className="rounded-2xl bg-white mx-3 px-3 py-4 mb-12">
            <div className="terms-1">
                <h1 className="text-xl font-bold">1. TERMS OF USE</h1>
                <p>1.1  Acceptance of the these terms of use. By accessing, reading, and making use of this Website and the Services, you are deemed to have reviewed, understood and accepted, on your own behalf and on behalf of any person on whose behalf you may be acting, these Terms of Use and agreed with the Company to be bound hereunder. For the purposes of these Terms of Use, “person” means any natural person, corporation, partnership, joint venture or any other incorporated or unincorporated entity, whether acting as an individual, fiduciary, or in any other capacity.If you do not wish to be bound by these Terms of Use, you may not use this Website or any of the Services.</p>
                <p>1.2 Changes of terms of use and website. The Company reserves the right, exercisable at any time at its sole discretion, to add to or remove, modify or otherwise change any part of these Terms of Use. Changes will be effective immediately at such time as the Terms of Use are posted on this Website. You should check the Terms of Use for changes by checking the date this page was last updated. If any change to the Terms of Use is not acceptable to you, you must discontinue your use of this Website and the Services immediately. Your continued use of this Website or any of the Services after any changes to the Terms and Conditions will constitute your unqualified acceptance of the changes. The Company may terminate, change, suspend or discontinue any aspect of this Website or the Services at any time without notice. Without limiting the generality of the foregoing, the Company may change the availability of any features, institute new, or amend existing fees or charges for the use of the Website, the Services, or any features included in the Website or the Services, add, remove, modify or otherwise change any content on this Website, and impose limits on certain features or restrict access to parts or all of this Website. The Company reserves the right, but not the duty, to correct any errors or omissions in any portion of this Website at any time and without notice.</p>
                <p>1.3 Other agreements. These Terms of Use are in addition to and supplementary to any other agreements that you or any person you represent have or may enter into with the Company concerning your dealings with them, including any information, products or services provided by the Company. In the event of any inconsistency or conflict between the provisions of these Terms of Use and the provisions of any other agreement that you or any person you represent have with the Company, the provisions of these Terms of Use shall govern regarding your access to and use of the Website and the Services.</p>
            </div>
            <div className="terms-2">
            <h1 className="text-xl font-bold">2. RISK WARNING</h1>
            <p>2.1 Buying, selling and investing in cryptocurrencies can be risky. The risk of loss in trading or holding cryptocurrency can be substantial. You should therefore carefully consider whether trading or holding cryptocurrency is suitable for you in light of your financial condition. In considering whether to trade or hold cryptocurrency, you should be aware that the price or value of cryptocurrency can change rapidly, decrease, and potentially even fall to zero.</p>
            <p>2.2 The cryptocurrencies market information relating to the past performance of an investment is not necessarily a guide to its performance in the future. The value of investments or income from them may go down as well as up. Like stocks and shares as well, cryptocurrencies are valued from second to second, their bid and offer value fluctuates sometimes widely. The degrees of fluctuation of prices vary significantly and the value of higher volatility funds may change suddenly. The value of investments may rise or fall due to the volatility of world markets, interest rates and capital values or, for investments held in overseas markets, changes in the rate of exchange in the currency in which the investments are denominated. You may not necessarily get back the amount you invested.</p>
            <p>2.3 You know and understand cryptocurrency trading also has certain risks which can cause a complete loss to zero. As cryptocurrencies are no official currency and the legal status is still undefined, their legal nature is subject of change under different jurisdictions. Unlike official currencies, which are backed up by governments or other legal entities like the FED, ECB or others, cryptocurrencies are a private currency, generated by all the world. There is no central bank that could take corrective measures to protect the value of the cryptocurrencies at a possible crisis.</p>
            <p>2.4 You know and understand cryptocurrency trading could be affected by hackers, change of laws, official restrictions, frauds, technical issues, collapse of infrastructure and many other possible threats.</p>
            <p>2.5 All content provided through this website is only for your personal information and use, and is not intended to address your particular requirements or to be relied upon in making (or refraining from making) any specific investment or other decision. Such content shall not constitute any form of advice or recommendation by bitnex. Furthermore, there may be additional risks that bitnex have not foreseen or named in this Terms of Use.</p>
            <p>2.6 bitnex does not provide any investment advice in connection with the services contemplated by these Terms of Use. We only provide information on the price, range, volatility of cryptocurrencies. Any decisions to buy or sell cryptocurrencies are made on your decision solely. bitnex will not be liable for any loss you might face.
</p>
            <p>2.7 If you are unsure about any specific investment or other decision, you should obtain appropriate expert independent advice and assess carefully whether your financial background is suitable for trading cryptocurrencies. Your decisions and investments are subject to your personal responsibility.</p>
            </div>
            <div className="terms-3">
            <h1 className="text-xl font-bold">3. REGISTRATION AND ACCOUNT OBLIGATIONS</h1>
            <p>3.1 You must be 18 years old or older to register and use our service.</p>
            <p>3.2 Only one registration per person is allowed. You must keep your registration information up to date.</p>
            <p>3.3 You must choose an email address which gives you frequent access to emails sent to that address, as we need to be able to contact you short notice. You must keep your password confidential.</p>
            <p>3.4 You must not, (1) impersonate or try to impersonate another person, (2) disclose your password to anyone else, (3) allow anyone else use your account or (4) use anyone else account.</p>
            <p>3.5 You are responsible for everything done using your account especially all damages may caused. If you think that someone else may have access to, or be using, your password or account, you must inform us as soon as possible by using online support.</p>
            <p>3.6 From time to time, we may restrict access to some parts of this site, or this entire site, to users who have registered with us for certain reasons.</p>
            <p>3.7 You are obliged to treat your user identification code, password or any other piece of information as part of our security procedures as confidential, and you must not disclose it to any third party. bitnex has the right to disable any account, if in our opinion you have failed to comply with any of the provisions of these terms and conditions until proven wrong by the user.
</p>
            </div>
            <div className="terms-1">
            <h1 className="text-xl font-bold">4.IDENTITY VERIFICATION</h1>
            <p>4.1 bitnex implements and maintains the highest standards of Know Your Customer (“KYC”) processes and controls as part of our commitment to combating fraud and assisting in the prevention of money laundering and terrorist financing. While our industry is largely unregulated, bitnex voluntarily adheres to local and international compliance standards in relation to customer due diligence. To ensure we meet these standards, our customers are required to provide certain personal details and documents when opening a bitnex Account (“Identity Verification”). The nature and extent of the Identity Verification required will depend upon which of our supported countries you are resident in, and the deposit and withdrawal limits that you wish to apply to your bitnex Account. In certain circumstances, bitnex may also perform enhanced due diligence (“EDD”) procedures in relation to your bitnex Account. You accept and agree that you will remain subject to such procedures at all times. For identity verification contact our site online support. You accept and agree that there may be delays in accessing your bitnex Account, or in carrying out transactions through your bitnex Account, while we undertake any Identity Verification and/or EDD procedures. Retention of information. bitnex is required to retain certain information and documentation obtained as part of the Identity Verification and EDD procedures. These requirements apply even when you have terminated your relationship with bitnex. We reserve the right to keep such information and documentation for the required period and you accept and agree that information and documentation you provide to bitnex may be retained by us, including following the closure of your bitnex Account.</p>
            <p>4.2 To activate your account and start transacting, you should to transfer funds to your new account by making a qualifying deposit that should be done by one payment. However, internal exchange transactions are not considered while classifying your account as activate accounts. This deposit is only required for new users as a security measure, you will receive the deposit on your account and you will be able to withdraw it instantly. This procedure name is wallet-wallet verification, and it means for you that nobody can access your account and make withdrawal without your permission.</p>
            <p>4.3 bitnex RESERVES THE RIGHT TO, AT ANY TIME: restrict or suspend your bitnex Account when we, in our sole discretion, consider it necessary to carry out further Identity Verification and/or EDD; or terminate your bitnex Account if you provide, or we suspect you have provided, false information or refuse to provide information we require for Identity Verification and/or EDD.</p>
            </div>
            <div className="terms-1"><h1 className="text-xl font-bold">5.EXCHANGE</h1></div>
            <p>5.1 The bitnex Exchange is an order book exchange platform for cryptocurrencies that is intended for use by customers with experience in and/or knowledge of similar platforms. Any person using the bitnex Exchange does so entirely at their own risk. The bitnex Exchange is not offered to customers in all jurisdictions. This section of the Terms applies to you if you access and/or use the bitnex Exchange.</p>
            <p>5.2 bitnex may, at any time and in our sole discretion, refuse any trade, impose limits on the trade amount permitted, or impose any other conditions or restrictions upon your use of the bitnex Exchange that we deem necessary. We may, for example, limit the number of open orders that you may establish or restrict trades from certain locations. bitnex reserves the right to take such action without prior notice.</p>
            <p>5.3 IN ACCESSING AND/OR USING THE bitnex EXCHANGE FOR ANY PURPOSE, YOU AGREE AND ACCEPT THAT: all trades executed on the bitnex Exchange are executed automatically, based on the parameters of your order instructions, and cannot be reversed. In the case of technical issues affecting bitnex internal systems, bitnex may, where possible and in its sole discretion, take steps to reverse or otherwise amend a trade. By using the bitnex Exchange, you accept and agree to all applicable fees; bitnex makes no guarantee that the bitnex Exchange will be available without interruption; that there will be no delays, failures, errors, omissions or loss of transmitted information; or that any order will be executed, accepted, recorded, or remain open;</p>
            <div className="terms-1"><h1 className="text-xl font-bold">6.TRANSACTIONS</h1></div>
            <p>6.1 Transaction Refusal. We may refuse to enter into a transaction, or we may terminate a particular transaction or all current transactions that you have outstanding with us, without notice to you: if you fail to make any payment or make payment from a blockchain account from which you are doing so unlawfully; if you fail to provide any material information we have requested or any information or warranty that you have given to us is, or becomes in our opinion, materially inaccurate, incorrect or misleading; in the event of your death or loss of mental capacity; if a serious dispute has arisen between us; if the performance of our obligations under this agreement becomes unlawful; if you terminate this agreement in accordance with clause 7 below; You must notify us immediately if you become aware of any event referred to in this paragraph happening or being likely to happen.</p>
            <p>6.2 In the event that we refuse a transaction and where it is lawful to do so, we will purchase at the prevailing market rate, the equivalent in your chosen cryptocurrency with the gross value of your deposit less any expenses, premiums, commissions or other fees incurred by us. The balance will then be sent to your Default Address. In the event that we incur a loss on the transaction, you will be liable to pay us the full amount of that loss.</p>
            <p>6.3 You acknowledge that under certain rare circumstances, we may be obligated to freeze your account completely and retain any funds that we are holding on your behalf pending further investigation.</p>
            <p>6.4 You acknowledge that the amount of any loss realized on the termination of a transaction is a debt payable by you and agree that we may immediately deduct the total amount of any loss (together with any expenses, premiums, commissions or other fees incurred by us) from any funds we are holding for you, including any monies you have paid to us in relation to any transaction. If the amount we are seeking to recover exceeds the amount of any funds held by us on your behalf, you agree to pay the balance within 7 days of being notified of the total amount due.</p>
            <p>6.5 We will not pay you any profit arising from the termination of a transaction in any circumstances.</p>
            <p>6.6 You agree that we may charge you interest on any sum that remains payable to us after we terminate any or all of your transactions at a rate of 5% per. Interest will accrue and will be calculated daily and be compounded monthly from the date payment was due until the full payment is received by us from you.</p>
            <p>6.7 If we refuse or terminate a transaction and where it is lawful to do so, we will send you a written statement explaining the amount of any sums that may be payable to us and the amount of any sums being withheld by us.</p>
            <div className="terms-1"><h1 className="text-xl font-bold">7.FEES</h1></div>
            <p>7.1 External fees. Every cryptocurrency transaction must be added to the blockchain, the official public ledger of all completed transactions, in order to be considered a successful and valid transfer. The work of validating transactions and adding them to the blockchain is done by miners, which are powerful computers that make up a portion of the network and confirm its transactions. Miners spend vast amounts of computing power and energy doing this for a financial reward: with every block (a collection of transactions) added to the blockchain comes a bounty called a block reward, as well as all fees sent with the transactions that were confirmed and included in the block. For this reason, miners have a financial incentive to prioritize the validation of transactions that include a higher fee. For someone looking to send funds and get a quick confirmation, the appropriate fee to include depends on the cryptocurrency being sent and can vary greatly, depending on a number of factors, such as transaction size and network conditions. Your wallet will automatically calculate the appropriate fee for sending your chosen cryptocurrency. The fee for sending ether is static (you can view the fee for sending ether by clicking “Send” and selecting Ether as the currency), while the fees for sending bitcoin, bitcoin cash, and stellar are dynamic and will be calculated by your wallet after you input the amount you want to send. This article explains bitcoin transaction fees in greater detail.</p>
            <p>7.2 Internal fees. The Our Digital Exchange shall enable matching of buy and sell orders between Users. The latest information on the time for settlement of any transactions and the costs and fees associated with transactions shall be as published on our Site from time to time. According to our rules, for each user there is a mandatory commission for all deposits, and for all withdrawals (1%). We trade at a variable percentage above market rate to cover our operating costs and to allow our vendors to make a profit. The trade-off for this is ease of use and the speed of the service - we are not the cheapest, but we try to be the best! Everything depends on the loading of our system and the magnitude of the operation.</p>
            <p>7.3 Collection-Related Costs. If you fail to pay fees or any other amounts owed to Payward under these Terms and Payward refers your account(s) to a third party for collection, then Payward will charge you the lesser of an 18% collection fee or the maximum percentage permitted by applicable law, to cover Paywar collection-related costs.</p>
            <p>7.4 At the first withdrawal of funds, users must pay a tax of 18% of the amount of your withdrawal. (One-time)</p>
            <div className="terms-1"><h1 className="text-xl font-bold">8.SECURITY</h1></div>
            <p>8.1 ACCOUNT SECURITY. bitnex TAKES SECURITY VERY SERIOUSLY AND THE MEASURES WE HAVE IN PLACE TO PROTECT YOUR bitnex ACCOUNT HOWEVER, YOU ARE SOLELY RESPONSIBLE FOR: maintaining adequate security and control over your bitnex Account sign-in details, including but not limited to any passwords, personal identification numbers (PINs), API keys, or any other codes associated with your bitnex Account; enabling any additional security features available to you, including the activation of two factor authentication on your bitnex account; keeping your contact details up to date so that you can receive any notices or alerts we may send to you in relation to security; maintaining security and control over the email mailbox, phone number and two-factor authentication applications or devices associated with your bitnex Account;</p>
            <p>8.2 Failure to take the above measures, and any other security measures available to you, may result in unauthorised access to your bitnex Account and the loss or theft of any cryptocurrency and/or Local Currency balances held in your bitnex Wallet or any linked bank account(s) and/or saved credit or debit card(s). bitnex shall have no liability to you for or in connection with any unauthorised access to your bitnex Account, where such unauthorised access was due to no fault of bitnex, and/or any failure by you to act upon any notice or alert that we send to you.</p>
            <p>8.3 The security of your bitnex Account may be compromised, or interruption caused to it, by phishing, spoofing or other attack, computer viruses, spyware, scareware, Trojan horses, worms or other malware that may affect your computer or other equipment. bitnex strongly recommends that you regularly use reputable virus screening and prevention software and remain alert to the fact that SMS, email services and search engines are vulnerable to spoofing and phishing attacks.</p>
            <p>8.4 Care should be taken in reviewing messages purporting to originate from bitnex and, should you have any uncertainty regarding the authenticity of any communication, you should log in to your bitnex Account through the bitnex website and not any other domain name or website purporting to be, or to be related to, bitnex to review any transactions or required actions. To the maximum extent permitted by applicable law, you accept and agree that you have full responsibility for all activity that occurs in or through your bitnex Account and accept all risks of any unauthorised or authorised access to your bitnex Account.</p>
            <p>8.5 To withdraw funds user need to synchronize an account on our exchange with external wallet address.</p>
            <p>8.6 Private keys. bitnex securely stores all Supported Cryptocurrency private keys (“Private Keys”) associated with any bitnex Account. You accept and agree that bitnex shall retain full ownership and control of the Private Keys associated with your bitnex Account and that you shall have no control of, access to, or the ability to use, such Private Keys</p>
            <p>8.7 FOR EXAMPLE, BUT WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, bitnex WILL NOT: accept or adhere to any instruction to sign any data with a Private Key; give access to any funds associated with your private keys, other than those of the Supported Cryptocurrency associated with your cryptocurrency wallet; give access to any funds associated with your private keys, other than those of the Supported Cryptocurrency associated with your cryptocurrency wallet;
</p>
            {/* <div className="terms-1"><h1 className="text-xl font-bold"></h1></div>
            <div className="terms-1"><h1 className="text-xl font-bold"></h1></div>
            <div className="terms-1"><h1 className="text-xl font-bold"></h1></div>
            <div className="terms-1"><h1 className="text-xl font-bold"></h1></div>
            <div className="terms-1"><h1 className="text-xl font-bold"></h1></div>
            <div className="terms-1"><h1 className="text-xl font-bold"></h1></div>
            <div className="terms-1"><h1 className="text-xl font-bold"></h1></div> */}
        </div>
        <Footer/>
    </div>
  )
}

export default page