import React from 'react'
import './privacy.css'
import Footer from '../footer/Footer'

const page = () => {
  return (
    <>
      <div className='mt-20'>
        <div className="my-4">
            <h1 className='text-center font-bold text-2xl'>Privacy Policy</h1>
        </div>
        <div className="privacy_ mx-3 p-3">
            <h1 className='font-bold text-2xl'>General</h1>
            <p className='mb-3'>Bitnex Financial Company and its affiliates (hereinafter, 'bitnex Financial Company', 'bitnex', 'we', 'us' or 'our') are committed to protecting and respecting your privacy. This Privacy Policy (together with our Terms of Use) governs our collection, processing and use of your Personal Information. We define 'Personal Information' as information which identifies you personally, e.g. your name, address, e-mail address, trades </p>
            <h1 className='font-bold text-2xl'>Who is bitnex</h1>
            <p className='mb-3'>Bitnex Australia’s largest fully regulated and licensed AML/CTF compliant AUSTRAC registered Dual Gateway Exchange Platform. Buy, sell, send, receive and trade cryptocurrencies.</p>
            <h1 className='font-bold text-2xl'>The types of Personal Information which we collect may include:</h1>
            <p className='mb-3'>We will process your Personal Information only for the purpose(s) of providing to you the service(s) that you ask us to provide you and to satisfy the legal obligations stemming from regulatory obligations that arise from providing you the service(s)</p>
            <h1 className='font-bold text-2xl'>IP Addresses</h1>
            <p className='mb-3'>We may collect information about your computer, including where available your IP address, operating system and browser type, for system administration and to report aggregate information to our advertisers. This is statistical data about our users' browsing actions and patterns and will not be used to identify any individual unless that same individual.</p>
            <h1 className='font-bold text-2xl'>Cookies</h1>
            <p className='mb-3'>We use a browser feature known as a 'cookie', which assigns a unique identification to your computer. Cookies are typically stored on your computer's hard drive. Information collected from cookies is used by us to evaluate the effectiveness of our Site, analyze trends, and administer the Platform. The information collected from cookies allows us to determine such things as which parts of our Site are most visited and difficulties our visitors may experience in accessing our Site. With this knowledge, we can improve the quality of your experience on the Platform by recognizing and delivering more of the most desired features and information, as well as by resolving access difficulties. We also use cookies and/or a technology known as web bugs or clear gifs, which are typically stored in emails to help us confirm your receipt of, and response to, our emails and to provide you with a more personalized experience when using our Site. We use third party service provider(s), to assist us in better understanding the use of our Site. Our service provider(s) will place cookies on the hard drive of your computer and will receive information that we select that will educate us on such things as how visitors navigate around our site, what products are browsed, and general Transaction information. Our service provider(s) analyses this information and provides us with aggregate reports. The information and analysis provided by our service provider(s) will be used to assist us in better understanding our visitors' interests in our Site and how to better serve those interests. The information collected by our service provider(s) may be linked to and combined with information that we collect about you while you are using the Platform. Our service provider(s) is/are contractually restricted from using information they receive from our Site other than to assist us. By using our Site you are agreeing that we may use cookies for the purposes set out above. The company will keep records of all transfers of Personal Information to third parties and this information, where possible, can be provided to you.</p>
            <h1 className='font-bold text-2xl'>Disclosure of Personal Information</h1>
            <p className='mb-3'>We use the Personal Information for the purposes indicated at the time you provide us with such information, and/or otherwise for the purposes set out in this Privacy Policy and/or as otherwise permitted by law. We may make available the Personal Information that you provide to us to our affiliates, agents, representatives, trusted service providers and contractors for these limited purposes upon your express consent or for and during the provision of the service that you would have requested. We may also share Users’ Personal Information with financial institutions, insurance companies or other companies in the case of a merger, divestiture, or other corporate re-organisation and notify you of such sharing of your information to be able to exercise any of your rights where applicable. We may also share Users' Personal Information with law enforcement or regulatory agencies, as may be required by law. We may not be able to inform you of such sharing of data due to legal restrictions. Any third party which receives or has access to Personal Information shall be required by us to protect such Personal Information and to use it only to carry out the services they are performing for you or for bitnex, unless otherwise required or permitted by law. Such a third party, except for regulatory authorities, would be contractually bound to adhere to the same security and confidentiality policies as bitvevo and assume the same responsibilities as bitvevo. The legitimate exercise of any of your rights with bitvevo will also be notified to be applied by any such third parties having been given access to your Personal Information. We will ensure that any such third party is aware of our obligations under this Privacy Policy and we will enter into contracts with such third parties by which they are bound by terms no less protective of any Personal Information disclosed to them than the obligations we undertake to you under this Privacy Policy or which are imposed on us under applicable data protection laws.</p>
            <h1 className='font-bold text-2xl'>Your rights</h1>
            <p className='mb-3'>You have the right to access your Personal Information and to require the correction, updating and blocking of inaccurate and/or incorrect data by sending an email to us at e-mail mentioned on the website (out e-mail), you can do these actions in your account profile page yourself (if applicable). Upon your written request at our e-mail, we will inform you of the Personal Information relating to you that we hold and the use and general disclosure of your Personal Information. We will also give you a copy of the Personal Information we have retained. There may be a minimal charge for providing you additional copies of your Personal Information to cover administrative costs. You may also request the deletion or destruction of both the Account and Personal Information by sending an email to our e-mail. Menxbit will action your request immediately, except, where this is not consistent with its legal and regulatory obligations.You may also ask us to transfer your Personal Information to another controller of your choice. To ensure the confidentiality, integrity and availability of your information to yourself, we may request you to confirm your identity by providing identification documentation and/or other methods prior to assisting you in exercising any of your rights. іf you refuse to prove your identity, we may decline to take actions in respect of your data, save restricting processing, until we can ensure that such actions are the true wish of the data subject. In the carrying out of our services we may use automated processing and profiling to reduce the risks of fraud, money laundering and abuse of our services. Through this automated processing, we carry out an analysis of your identification, transactional and behavioral patterns. We may not able to provide you with some or all our services if you do not wish this automated processing to be carried out. If you feel that this processing might be detrimental to you, we can provide you with further information about this automated processing by contacting us on our e-mail.</p>
        </div>
      </div>
      <Footer/>
    </>
  )
}

export default page